name: Check Code Standarts

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm
        run: npm i -g npm@latest
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run tests
        run: npm run test --if-present

  lint:
    name: Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install npm
        run: npm i -g npm@latest
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Run linters
        run: npm run lint --if-present
